import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight,Clock3,Mail,MapPin,Phone } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { InnerHero } from "@/components/InnerHero";
import { ContactForm } from "@/components/ContactForm";
import { socialLinks } from "@/data/company";

export const metadata:Metadata={title:"Contact Startek | Start a Project",description:"Contact Startek to discuss digital marketing, web development, software solutions, printing, signage, packaging or integrated business solutions.",openGraph:{title:"Contact Startek | Start a Project",description:"Contact Startek to discuss digital marketing, web development, software solutions, printing, signage, packaging or integrated business solutions.",images:[]},twitter:{card:"summary",title:"Contact Startek | Start a Project",description:"Contact Startek to discuss digital marketing, web development, software solutions, printing, signage, packaging or integrated business solutions.",images:[]}};

const contactCards=[{icon:Mail,title:"Email",text:"Official email address to be added"},{icon:Phone,title:"Phone",text:"Official phone number to be added"},{icon:MapPin,title:"Location",text:"Sri Lanka · Full address to be added"},{icon:Clock3,title:"Availability",text:"Official business hours to be added"}];
export default function ContactPage(){return <><Navbar/><main><InnerHero eyebrow="Contact Startek" title={"Let's build\nsomething useful."} text="Tell us where you want to go. We’ll help identify the right combination of strategy, digital, development and production." label="Project enquiries"/><section className="section contact-section"><div className="container contact-layout"><div className="contact-primary"><div className="section-heading"><p className="eyebrow"><span>+</span>Project enquiry</p><h2>Start with the brief.</h2><p className="section-copy">Share the essentials below. Required fields are marked with an asterisk.</p></div><ContactForm/></div><aside className="contact-aside"><div><p className="eyebrow"><span>+</span>Direct contact</p><h2>Official details are being prepared.</h2><p>Startek will only publish verified business contact information. Until those details are supplied, please use the project form to prepare your enquiry.</p></div><div className="contact-card-grid">{contactCards.map(card=><article key={card.title}><card.icon size={18}/><span>{card.title}</span><strong>{card.text}</strong></article>)}</div><div className="contact-social"><p>Official social channels</p>{socialLinks.map(link=><Link href={link.href} key={link.label} target="_blank" rel="noreferrer">{link.label}<ArrowUpRight size={15}/></Link>)}</div></aside></div></section></main><Footer/></>}
