import type { Metadata } from "next";
import { Link } from "@/components/AppLink";
import { ArrowUpRight } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { InnerHero } from "@/components/InnerHero";

export const metadata:Metadata={title:"Selected Work | Startek",description:"Startek is preparing approved project case studies across digital marketing, web development, software, printing and physical branding.",alternates:{canonical:"/work"},openGraph:{title:"Selected Work | Startek",description:"Approved Startek project case studies are being prepared for publication.",type:"website",url:"/work",images:[]},twitter:{card:"summary",title:"Selected Work | Startek",description:"Approved Startek project case studies are being prepared for publication.",images:[]}};

const categories=[{title:"Startek Digital",text:"Strategy, social media, creative, advertising and growth systems."},{title:"Startek Web Hub",text:"Websites, e-commerce, applications, integrations and ongoing support."},{title:"Startek Print Hub",text:"Business printing, signage, packaging, promotional products and physical branding."}];
export default function WorkPage(){return <><Navbar/><main><InnerHero eyebrow="Selected work" title={"Selected\nwork."} text="We are preparing a selection of approved Startek projects and case studies for publication." label="Portfolio publishing in progress"/><section className="section work-gallery-section"><div className="container"><div className="section-heading"><p className="eyebrow"><span>+</span>Coming to the portfolio</p><h2>Real work. Clear context.</h2><p className="section-copy">Each published case study will explain the requirement, approach and delivered solution without unsupported results or invented client details.</p></div><div className="work-category-grid">{categories.map((category,i)=><article key={category.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{category.title}</h2><p>{category.text}</p></article>)}</div><div className="portfolio-note"><strong>Our latest projects are being prepared for showcase.</strong><p>Need a relevant example for an upcoming project? Start a conversation and tell us what you are planning.</p><Link className="text-link" href="/contact">Discuss Your Project <ArrowUpRight size={16} aria-hidden="true"/></Link></div></div></section><section className="page-cta"><div className="container"><div><p className="eyebrow"><span>+</span>Your project</p><h2>Ready to build something useful?</h2></div><Link className="button" href="/contact">Start a Project <ArrowUpRight size={16} aria-hidden="true"/></Link></div></section></main><Footer/></>}
