import type { Metadata } from "next";
import { Link } from "@/components/AppLink";
import { ArrowUpRight } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { InnerHero } from "@/components/InnerHero";

export const metadata:Metadata={title:"Selected Work | Startek",description:"Explore Startek capabilities across digital marketing, web development, software, printing and physical branding.",alternates:{canonical:"/work"},openGraph:{title:"Selected Work | Startek",description:"Explore Startek capabilities across digital, web technology and physical branding.",type:"website",url:"/work",images:[]},twitter:{card:"summary",title:"Selected Work | Startek",description:"Explore Startek capabilities across digital, web technology and physical branding.",images:[]}};

const categories=[{title:"Startek Digital",text:"Strategy, social media, advertising, creative content and digital growth."},{title:"Startek Web Hub",text:"Websites, e-commerce platforms, applications, integrations and technical support."},{title:"Startek Print Hub",text:"Printing, signage, packaging, promotional products and physical branding."}];
export default function WorkPage(){return <><Navbar/><main><InnerHero eyebrow="Selected work" title={"Selected\nwork."} text="Startek projects span digital marketing, websites, applications, printing, signage, packaging and brand execution."/><section className="section work-gallery-section"><div className="container"><div className="section-heading"><p className="eyebrow"><span>+</span>Project Showcase</p><h2>Built Across Three Disciplines.</h2></div><div className="work-category-grid">{categories.map((category,i)=><article key={category.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{category.title}</h2><p>{category.text}</p></article>)}</div><div className="portfolio-note"><strong>Detailed Startek case studies are being prepared for publication.</strong><Link className="text-link" href="/contact">Discuss Your Project <ArrowUpRight size={16} aria-hidden="true"/></Link></div></div></section><section className="page-cta"><div className="container"><div><p className="eyebrow"><span>+</span>Your project</p><h2>Ready to build something useful?</h2></div><Link className="button" href="/contact">Discuss Your Project <ArrowUpRight size={16} aria-hidden="true"/></Link></div></section></main><Footer/></>}
